// https://lottiefiles.com/110216-okokok-green
// https://assets3.lottiefiles.com/packages/lf20_iktgjsbj.json

export const check = (color: Array<number>, secondColor?: Array<number>) => {
  return {
    nm: 'BICOO - Check',
    mn: '',
    layers: [
      {
        ty: 4,
        nm: 'Check',
        mn: '',
        sr: 1,
        st: 0,
        op: 40,
        ip: 0,
        hd: false,
        cl: '',
        ln: '',
        ddd: 0,
        bm: 0,
        tt: 0,
        hasMask: false,
        td: 0,
        ao: 0,
        ks: {
          a: {a: 0, k: [-1.312, 6, 0], ix: 1},
          s: {a: 0, k: [200, 200, 100], ix: 6},
          sk: {a: 0, k: 0},
          p: {a: 0, k: [100, 100, 0], ix: 2},
          sa: {a: 0, k: 0},
          o: {a: 0, k: 100, ix: 11},
          r: {a: 0, k: 0, ix: 10},
        },
        ef: [],
        shapes: [
          {
            ty: 'gr',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Shape 1',
            ix: 1,
            cix: 2,
            np: 3,
            it: [
              {
                ty: 'sh',
                bm: 0,
                cl: '',
                ln: '',
                hd: false,
                mn: 'ADBE Vector Shape - Group',
                nm: 'Path 1',
                ix: 1,
                d: 1,
                ks: {
                  a: 0,
                  k: {
                    c: false,
                    i: [
                      [0, 0],
                      [0, 0],
                      [0, 0],
                    ],
                    o: [
                      [0, 0],
                      [0, 0],
                      [0, 0],
                    ],
                    v: [
                      [-15.75, 8],
                      [-8, 16],
                      [13.125, -4],
                    ],
                  },
                  ix: 2,
                },
              },
              {
                ty: 'tm',
                bm: 0,
                cl: '',
                ln: '',
                hd: false,
                mn: 'ADBE Vector Filter - Trim',
                nm: 'Trim Paths 1',
                ix: 2,
                e: {a: 0, k: 0, ix: 2},
                o: {a: 0, k: 0, ix: 3},
                s: {
                  a: 1,
                  k: [
                    {o: {x: 0.333, y: 0}, i: {x: 0.667, y: 1}, s: [0], t: 25},
                    {
                      o: {x: 0.167, y: 0.167},
                      i: {x: 0.833, y: 0.833},
                      s: [100],
                      t: 33,
                    },
                  ],
                  ix: 1,
                },
                m: 1,
              },
              {
                ty: 'st',
                bm: 0,
                cl: '',
                ln: '',
                hd: false,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                lc: 2,
                lj: 2,
                ml: 1,
                o: {a: 0, k: 100, ix: 4},
                w: {a: 0, k: 5, ix: 5},
                d: [],
                c: {a: 0, k: secondColor, ix: 3},
              },
              {
                ty: 'tr',
                a: {a: 0, k: [0, 0], ix: 1},
                s: {a: 0, k: [100, 100], ix: 3},
                sk: {a: 0, k: 0, ix: 4},
                p: {a: 0, k: [0, 0], ix: 2},
                r: {a: 0, k: 0, ix: 6},
                sa: {a: 0, k: 0, ix: 5},
                o: {a: 0, k: 100, ix: 7},
              },
            ],
          },
        ],
        ind: 0,
      },
      {
        ty: 4,
        nm: 'Circ Stroke',
        mn: '',
        sr: 1,
        st: 0,
        op: 40,
        ip: 0,
        hd: false,
        cl: '',
        ln: '',
        ddd: 0,
        bm: 0,
        tt: 0,
        hasMask: false,
        td: 0,
        ao: 0,
        ks: {
          a: {a: 0, k: [0, 0, 0], ix: 1},
          s: {
            a: 1,
            k: [
              {
                o: {x: 0.333, y: 0},
                i: {x: 0.667, y: 1},
                s: [200, 200, 100],
                t: 9,
              },
              {
                o: {x: 0.333, y: 0},
                i: {x: 0.667, y: 1},
                s: [160, 160, 100],
                t: 17,
              },
              {
                o: {x: 0.333, y: 0},
                i: {x: 0.667, y: 1},
                s: [240, 240, 100],
                t: 22,
              },
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [200, 200, 100],
                t: 26,
              },
            ],
            ix: 6,
          },
          sk: {a: 0, k: 0},
          p: {a: 0, k: [98.045, 98.045, 0], ix: 2},
          sa: {a: 0, k: 0},
          o: {a: 0, k: 100, ix: 11},
          r: {a: 0, k: 0, ix: 10},
        },
        ef: [],
        shapes: [
          {
            ty: 'gr',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Group',
            nm: 'Ellipse 1',
            ix: 1,
            cix: 2,
            np: 3,
            it: [
              {
                ty: 'el',
                bm: 0,
                cl: '',
                ln: '',
                hd: false,
                mn: 'ADBE Vector Shape - Ellipse',
                nm: 'Ellipse Path 1',
                d: 1,
                p: {a: 0, k: [0, 0], ix: 3},
                s: {a: 0, k: [60, 60], ix: 2},
              },
              {
                ty: 'tm',
                bm: 0,
                cl: '',
                ln: '',
                hd: false,
                mn: 'ADBE Vector Filter - Trim',
                nm: 'Trim Paths 1',
                ix: 2,
                e: {a: 0, k: 0, ix: 2},
                o: {a: 0, k: 0, ix: 3},
                s: {
                  a: 1,
                  k: [
                    {o: {x: 0.333, y: 0}, i: {x: 0.667, y: 1}, s: [0], t: 0},
                    {
                      o: {x: 0.167, y: 0.167},
                      i: {x: 0.833, y: 0.833},
                      s: [100],
                      t: 9,
                    },
                  ],
                  ix: 1,
                },
                m: 1,
              },
              {
                ty: 'st',
                bm: 0,
                cl: '',
                ln: '',
                hd: false,
                mn: 'ADBE Vector Graphic - Stroke',
                nm: 'Stroke 1',
                lc: 2,
                lj: 2,
                ml: 1,
                o: {a: 0, k: 100, ix: 4},
                w: {a: 0, k: 3, ix: 5},
                d: [],
                c: {a: 0, k: color, ix: 3},
              },
              {
                ty: 'tr',
                a: {a: 0, k: [0, 0], ix: 1},
                s: {a: 0, k: [100, 100], ix: 3},
                sk: {a: 0, k: 0, ix: 4},
                p: {a: 0, k: [0.978, 0.978], ix: 2},
                r: {a: 0, k: 0, ix: 6},
                sa: {a: 0, k: 0, ix: 5},
                o: {a: 0, k: 100, ix: 7},
              },
            ],
          },
        ],
        ind: 1,
      },
      {
        ty: 4,
        nm: 'Circ Verde',
        mn: '',
        sr: 1,
        st: 0,
        op: 40,
        ip: 0,
        hd: false,
        cl: '',
        ln: '',
        ddd: 0,
        bm: 0,
        tt: 0,
        hasMask: false,
        td: 0,
        ao: 0,
        ks: {
          a: {a: 0, k: [0, 0, 0], ix: 1},
          s: {
            a: 1,
            k: [
              {o: {x: 0.333, y: 0}, i: {x: 0.667, y: 1}, s: [0, 0, 100], t: 14},
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [200, 200, 100],
                t: 25,
              },
            ],
            ix: 6,
          },
          sk: {a: 0, k: 0},
          p: {a: 0, k: [100, 100, 0], ix: 2},
          sa: {a: 0, k: 0},
          o: {
            a: 1,
            k: [
              {o: {x: 0.167, y: 0.167}, i: {x: 0.833, y: 0.833}, s: [0], t: 14},
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [98],
                t: 25,
              },
            ],
            ix: 11,
          },
          r: {a: 0, k: 0, ix: 10},
        },
        ef: [],
        shapes: [
          {
            ty: 'el',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Shape - Ellipse',
            nm: 'Ellipse Path 1',
            d: 1,
            p: {a: 0, k: [0, 0], ix: 3},
            s: {a: 0, k: [64, 64], ix: 2},
          },
          {
            ty: 'fl',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Graphic - Fill',
            nm: 'Fill 1',
            c: {a: 0, k: color, ix: 4},
            r: 1,
            o: {a: 0, k: 100, ix: 5},
          },
        ],
        ind: 2,
      },
      {
        ty: 4,
        nm: 'Ola 1',
        mn: '',
        sr: 1,
        st: 0,
        op: 40,
        ip: 0,
        hd: false,
        cl: '',
        ln: '',
        ddd: 0,
        bm: 0,
        tt: 0,
        hasMask: false,
        td: 0,
        ao: 0,
        ks: {
          a: {a: 0, k: [0, 0, 0], ix: 1},
          s: {
            a: 1,
            k: [
              {o: {x: 0.333, y: 0}, i: {x: 0.667, y: 1}, s: [0, 0, 100], t: 14},
              {
                o: {x: 0.167, y: 0},
                i: {x: 0.833, y: 1},
                s: [250, 250, 100],
                t: 27,
              },
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [230, 230, 100],
                t: 34,
              },
            ],
            ix: 6,
          },
          sk: {a: 0, k: 0},
          p: {a: 0, k: [100, 100, 0], ix: 2},
          sa: {a: 0, k: 0},
          o: {
            a: 1,
            k: [
              {o: {x: 0.167, y: 0.167}, i: {x: 0.833, y: 0.833}, s: [0], t: 14},
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [90],
                t: 27,
              },
            ],
            ix: 11,
          },
          r: {a: 0, k: 0, ix: 10},
        },
        ef: [],
        shapes: [
          {
            ty: 'el',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Shape - Ellipse',
            nm: 'Ellipse Path 1',
            d: 1,
            p: {a: 0, k: [0, 0], ix: 3},
            s: {a: 0, k: [64, 64], ix: 2},
          },
          {
            ty: 'fl',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Graphic - Fill',
            nm: 'Fill 1',
            c: {a: 0, k: color, ix: 4},
            r: 1,
            o: {a: 0, k: 100, ix: 5},
          },
        ],
        ind: 3,
      },
      {
        ty: 4,
        nm: 'Ola 2',
        mn: '',
        sr: 1,
        st: 0,
        op: 40,
        ip: 0,
        hd: false,
        cl: '',
        ln: '',
        ddd: 0,
        bm: 0,
        tt: 0,
        hasMask: false,
        td: 0,
        ao: 0,
        ks: {
          a: {a: 0, k: [0, 0, 0], ix: 1},
          s: {
            a: 1,
            k: [
              {o: {x: 0.333, y: 0}, i: {x: 0.667, y: 1}, s: [0, 0, 100], t: 14},
              {
                o: {x: 0.167, y: 0},
                i: {x: 0.833, y: 1},
                s: [280, 280, 100],
                t: 29,
              },
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [260, 260, 100],
                t: 36,
              },
            ],
            ix: 6,
          },
          sk: {a: 0, k: 0},
          p: {a: 0, k: [100, 100, 0], ix: 2},
          sa: {a: 0, k: 0},
          o: {
            a: 1,
            k: [
              {o: {x: 0.167, y: 0.167}, i: {x: 0.833, y: 0.833}, s: [0], t: 14},
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [60],
                t: 29,
              },
            ],
            ix: 11,
          },
          r: {a: 0, k: 0, ix: 10},
        },
        ef: [],
        shapes: [
          {
            ty: 'el',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Shape - Ellipse',
            nm: 'Ellipse Path 1',
            d: 1,
            p: {a: 0, k: [0, 0], ix: 3},
            s: {a: 0, k: [64, 64], ix: 2},
          },
          {
            ty: 'fl',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Graphic - Fill',
            nm: 'Fill 1',
            c: {a: 0, k: color, ix: 4},
            r: 1,
            o: {a: 0, k: 100, ix: 5},
          },
        ],
        ind: 4,
      },
      {
        ty: 4,
        nm: 'Ola 3',
        mn: '',
        sr: 1,
        st: 0,
        op: 40,
        ip: 0,
        hd: false,
        cl: '',
        ln: '',
        ddd: 0,
        bm: 0,
        tt: 0,
        hasMask: false,
        td: 0,
        ao: 0,
        ks: {
          a: {a: 0, k: [0, 0, 0], ix: 1},
          s: {
            a: 1,
            k: [
              {o: {x: 0.333, y: 0}, i: {x: 0.667, y: 1}, s: [0, 0, 100], t: 14},
              {
                o: {x: 0.167, y: 0},
                i: {x: 0.833, y: 1},
                s: [310, 310, 100],
                t: 31,
              },
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [290, 290, 100],
                t: 38,
              },
            ],
            ix: 6,
          },
          sk: {a: 0, k: 0},
          p: {a: 0, k: [100, 100, 0], ix: 2},
          sa: {a: 0, k: 0},
          o: {
            a: 1,
            k: [
              {o: {x: 0.167, y: 0.167}, i: {x: 0.833, y: 0.833}, s: [0], t: 14},
              {
                o: {x: 0.167, y: 0.167},
                i: {x: 0.833, y: 0.833},
                s: [30],
                t: 31,
              },
            ],
            ix: 11,
          },
          r: {a: 0, k: 0, ix: 10},
        },
        ef: [],
        shapes: [
          {
            ty: 'el',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Shape - Ellipse',
            nm: 'Ellipse Path 1',
            d: 1,
            p: {a: 0, k: [0, 0], ix: 3},
            s: {a: 0, k: [64, 64], ix: 2},
          },
          {
            ty: 'fl',
            bm: 0,
            cl: '',
            ln: '',
            hd: false,
            mn: 'ADBE Vector Graphic - Fill',
            nm: 'Fill 1',
            c: {a: 0, k: color, ix: 4},
            r: 1,
            o: {a: 0, k: 100, ix: 5},
          },
        ],
        ind: 5,
      },
    ],
    ddd: 0,
    h: 200,
    w: 200,
    meta: {
      a: '',
      k: '',
      d: '',
      g: '@lottiefiles/toolkit-js 0.18.1',
      tc: '#ffffff',
    },
    v: '5.1.1',
    fr: 30,
    op: 40,
    ip: 0,
    assets: [],
  };
};
